services:
  image-api:
    build: ./image-api
    volumes:
      - ./image-api/src:/app/src  # 코드만 마운트
    environment:
      - TZ=Asia/Seoul
    ports:
      - "8888:8080"
    depends_on:
      - db
  db:
    build: ./db
    ports:
      - 3306:3306
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/ssl:/etc/mysql/ssl
    env_file: .env
    environment:
      TZ: Asia/Seoul
    restart: always