services:
  image-api:
    build: ./image-api
    volumes:
      - ./image-api/src:/app/src  # 코드만 마운트
    environment:
      - TZ=Asia/Seoul
    ports:
      - "8888:8080"
    depends_on:
      - db
      - redis
    restart: always

  db:
    build:
      dockerfile: Dockerfile.mysql
    ports:
      - 3306:3306
    volumes:
      - ./db/data:/var/lib/mysql
    env_file: .env
    environment:
      TZ: Asia/Seoul
    restart: always

  redis:
    build: 
      dockerfile: Dockerfile.redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    env_file: .env
    environment:
      TZ: Asia/Seoul
    restart: always